# Setup
title:        zkfbdkf's blog
tagline:      ML, JAVA, C++, CV
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       zkfbdkf
  url:        https://github.com/zkfbdkf

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
